### PR TITLE
add unfinished-work-in-progress voting kimchi

### PR DESCRIPTION
**Pull request by david415**
depends on https://github.com/katzenpost/mailproxy/pull/27 AND https://github.com/katzenpost/core/pull/39 AND https://github.com/katzenpost/authority/pull/18

not even close to being merged. dot not merge.

### CODE REVIEW

**Comment by david415** [comment]
does @mixmasala care to replace this PR with a new more better one?

**Comment by mixmasala** [comment]
please see: https://github.com/mixmasala/authority/tree/voting.3
but we are not ready to merge this into master yet.

**Comment by mixmasala** [comment]
er: https://github.com/mixmasala/demotools/tree/kimchi_voting.0

**Comment by mixmasala** [comment]
https://github.com/katzenpost/tools/pull/5

**Pull request closed without merging**
