### PR TITLE
Add genconfig

### PR DESCRIPTION
**Pull request by mixmasala**
creates a separate tool to generate configuration files for test mixnets.

### CODE REVIEW

**Comment by david415** [comment]
cool! i will try to use this later and see how it works. i'm hoping it'll just use my loopback interface in such a way that spinning up a new mixnet will be easy. BTW i also have some helper bash scripts that i use to startup and shutdown the entire mixnet as well as remove logs.

**Comment by david415** [comment]
ok i've taken a brief look at this. we can't merge it until the voting pki is merged into master so let's keep that in mind.

**Comment by david415** [comment]
@mixmasala please resolve conflicts and merge

**Comment by mixmasala** [comment]
This is already in master somehow?

**Comment by mixmasala** [comment]
this is already in master

**Pull request closed without merging**
